### ISSUE TITLE
Glyph Data Axis's "Visible On" = "Last" does not show any axis, while "First" & "All" options works.

### ISSUE THREAD

**Issue by SMusento23** [zBritva/charticulator-visual-community#27]
Hi,

If in a given Data Axis, "Visible On" = "Last", Charticulator VC 1.2.0.0 does not show any axis: 

 "Visible On" = "Last" (missing):
![image](https://github.com/user-attachments/assets/7e1d34d5-e1d8-47dd-a9db-1b096441de36)

 "Visible On" = "First":
![image](https://github.com/user-attachments/assets/84f69668-3140-4a8e-87c1-a679ebdcaaa6)

"Visible On" = "All"
![image](https://github.com/user-attachments/assets/ba7630f8-3a14-44dd-91d7-a729183739ab)

See .pbix attachement:
[PWBI_2.131.1203_Chartic.VC_Editor_1.2.0.0_Issue Glyph Data Axis's Visible On Equal Last Not Showing.pbix.zip](https://github.com/user-attachments/files/16783277/PWBI_2.131.1203_Chartic.VC_Editor_1.2.0.0_Issue.Glyph.Data.Axis.s.Visible.On.Equal.Last.Not.Showing.pbix.zip)

**Comment by zBritva** [comment]
Thanks! 
I huess there is issue with marks. On the last glyph no marks with size greather than 0. And glyph size collapses into 0.
Because Data axis bound to glyph, it also has szie 0.

Workaround:

Add symbol to "Glyph 4" and set Fill property to None (to make it invisible):

![image](https://github.com/user-attachments/assets/43c77c7b-0bac-48dd-b667-a59fb54c8918)

**Comment by zBritva** [comment]
Fixed in View version
